### ISSUE TITLE
what gltf files work with ep13's loader?

### ISSUE THREAD

**Issue by hotcocoaNcode** [VictorGordan/opengl-tutorials#14]
Is there any way to identify which ones will load and which ones won't load? It seems very hit and miss, and I also can't get anything from blender working.

**Comment by VictorGordan** [comment]
Not really. It really isn't a good loader. It's mostly just to show how you
can make a very very basic glTF loader, so most models won't be loaded
properly if they are a bit more advanced 😅

**Comment by hotcocoaNcode** [comment]
alright, thanks
