### ISSUE TITLE
YoutubeOpenGL 5 - Shaders/shaderClass.cpp - Check for compile errors function

### ISSUE THREAD

**Issue by Sputn1kz** [VictorGordan/opengl-tutorials#3]
In the line :

`95: glGetProgramiv(shader, GL_COMPILE_STATUS, &hasCompiled)`
`95: glGetProgramiv(shader, GL_LINK_STATUS, &hasCompiled) // Corrected`

I was getting a empty compile error because for the program compiler check is a linking process right?

> The status of the link operation will be stored as part of the program object's state. This value will be set to GL_TRUE if the program object was linked without errors and is ready for use, and GL_FALSE otherwise. It can be queried by calling glGetProgramiv with arguments program and GL_LINK_STATUS.

`https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glLinkProgram.xhtml`

Amazing OpenGL course videos! Thank You.

**Comment by VictorGordan** [comment]
Yes, you are correct! 
This is what happens when you copy paste parts of your code and forget to change all the relevant parts haha 
I'll make sure to correct it asap :)

**Comment by VictorGordan** [comment]
Fixed in 73ce89a
