### ISSUE TITLE
5 shaders - compile errors

### ISSUE THREAD

**Issue by andreish** [VictorGordan/opengl-tutorials#8]
SHADER_COMPILATION_ERROR for:FRAGMENT
0(4) : error C7548: 'layout(location)' requires "#extension GL_ARB_separate_shader_objects : enable" before use
0(4) : error C0000: ... or #version 410
0(6) : error C7548: 'layout(location)' requires "#extension GL_ARB_separate_shader_objects : enable" before use
0(6) : error C0000: ... or #version 410
0(18) : error C5052: gl_Position is not accessible in this profile

SHADER_LINKING_ERROR for:PROGRAM
Fragment info
-------------
0(4) : error C7548: 'layout(location)' requires "#extension GL_ARB_separate_shader_objects : enable" before use
0(4) : error C0000: ... or #version 410
0(6) : error C7548: 'layout(location)' requires "#extension GL_ARB_separate_shader_objects : enable" before use
0(6) : error C0000: ... or #version 410
0(18) : error C5052: gl_Position is not accessible in this profile
(0) : error C2003: incompatible options for link

**Comment by VictorGordan** [comment]
For which tutorial is this?

**Comment by andreish** [comment]
tutorial 5, got it , I switched the vertex code with fragment code  . can be closed
